"""Generate weekly plan page with all dropdowns."""
import streamlit as st
import httpx
import pandas as pd
from datetime import date, timedelta
from ui.utils.api import API_BASE, get_auth_headers
from ui.utils.auth import require_auth


def render():
    require_auth()
    st.header("📅 Generate My Weekly Plan")

    with st.form("plan_form"):
        col1, col2 = st.columns(2)
        with col1:
            wake_options = [f"{h:02d}:{m:02d}" for h in range(4, 10) for m in (0, 30)]
            wake_time = st.selectbox("⏰ Wake Up Time", wake_options, index=4)

            sleep_options = [f"{h:02d}:{m:02d}" for h in range(20, 24) for m in (0, 30)]
            sleep_time = st.selectbox("🌙 Sleep Time", sleep_options, index=3)

            diet = st.selectbox("🥗 Diet Preference", ["veg", "non-veg", "vegan"])

        with col2:
            includes_gym = st.checkbox("🏋️ Include Gym")
            includes_yoga = st.checkbox("🧘 Include Yoga")
            includes_meditation = st.checkbox("🧠 Include Meditation", value=True)

            gym_duration = None
            if includes_gym:
                gym_mins = st.select_slider(
                    "🏋️ Gym Duration",
                    options=list(range(30, 121, 15)),
                    value=60,
                    format_func=lambda x: f"{x} mins",
                )
                gym_duration = gym_mins

        week_start = st.date_input("📆 Week Starting", value=date.today() + timedelta(days=(7 - date.today().weekday())))

        submitted = st.form_submit_button("✨ Generate My Weekly Plan", type="primary", use_container_width=True)

    if submitted:
        payload = {
            "week_start": str(week_start),
            "preferences": {
                "wake_time": wake_time, "sleep_time": sleep_time, "diet": diet,
                "includes_gym": includes_gym, "includes_yoga": includes_yoga,
                "includes_meditation": includes_meditation,
                "gym_duration_minutes": gym_duration or 60,
            },
        }
        with st.spinner("🤖 Agents are crafting your personalised plan…"):
            resp = httpx.post(f"{API_BASE}/plans/generate", json=payload, headers=get_auth_headers(), timeout=90)

        if resp.status_code == 201:
            plan = resp.json()
            st.success(f"✅ Plan generated by **{plan['llm_provider'].upper()}**")
            _render_plan_table(plan["days"])
        else:
            st.error(f"Generation failed: {resp.json().get('detail')}")


def _render_plan_table(days: list[dict]):
    st.subheader("Your Weekly Wellness Plan")
    df = pd.DataFrame(days)[["day_name", "wake_time", "breakfast", "lunch", "dinner",
                               "workout", "meditation", "book_recommendation", "sleep_time"]]
    df.columns = ["Day", "Wake", "Breakfast", "Lunch", "Dinner", "Workout", "Meditation", "Book", "Sleep"]
    st.dataframe(df, use_container_width=True, hide_index=True)
