# -*- coding: utf-8 -*-
"""demo1_middleware_observability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQsWZpmPrif90AZvv0GYzQqOgBhS2Y8o

# 🔬 Demo 1 — FastAPI Middleware & Observability
> **EY Backend Engineering Bootcamp — Day 9**

**Scenario:** You are an EY backend engineer on a global payments modernisation project. In this demo you will build and test the four middleware pillars — Logging, Metrics, Retry, and Circuit Breaker — that every production FastAPI service must have.

---
### Learning Objectives
- Attach HTTP middleware to a FastAPI app (logging + metrics)
- Use `structlog` for structured JSON logging with correlation IDs
- Expose a `/metrics` endpoint for Prometheus scraping
- Implement exponential-backoff retry with `tenacity`
- Implement a circuit breaker with `pybreaker`

### 🗺️ Road Map
```
Part 1 → Install deps
Part 2 → Logging middleware
Part 3 → Prometheus metrics middleware
Part 4 → Retry with tenacity
Part 5 → Circuit breaker with pybreaker
Part 6 → Run the full app (ngrok tunnel)
Extension Tasks →  Advanced challenges
```

## Part 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install fastapi uvicorn[standard] structlog tenacity pybreaker \
#              prometheus-client prometheus-fastapi-instrumentator \
#              httpx pyngrok nest-asyncio

import nest_asyncio
nest_asyncio.apply()  # Allow asyncio inside Colab's event loop
print('✅ Dependencies installed and asyncio patched')

"""---
## Part 2 — Structured Logging Middleware

Every request must carry a **correlation ID** so you can trace a single payment across 50 microservices.
We attach middleware that:
1. Reads `X-Correlation-Id` from the incoming request (or generates a new UUID)
2. Logs request start / end as structured JSON
3. Passes the correlation ID forward in the response
"""

import httpx
import structlog, logging, uuid, time, os
from collections import defaultdict, deque
from contextvars import ContextVar
from pathlib import Path
from threading import Lock
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from prometheus_fastapi_instrumentator import Instrumentator
from fastapi.responses import Response

CORRELATION_ID: ContextVar[str] = ContextVar('correlation_id', default='')
LOG_FILE = Path(__file__).resolve().with_name('middleware.ndjson')

root_logger = logging.getLogger()
root_logger.handlers.clear()
root_logger.setLevel(logging.INFO)

for handler in (logging.StreamHandler(), logging.FileHandler(LOG_FILE, encoding='utf-8')):
    handler.setFormatter(logging.Formatter('%(message)s'))
    root_logger.addHandler(handler)

# Configure structlog to output clean JSON and write to a local NDJSON file
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.stdlib.BoundLogger,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

log = structlog.get_logger('demo_middleware')

app = FastAPI(title='EY Payment API', version='1.0.0')

RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_MAX_REQUESTS = 100
_rate_limit_state = defaultdict(deque)
_rate_limit_lock = Lock()

@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    client_ip = request.headers.get('x-forwarded-for', request.client.host if request.client else 'unknown')
    client_ip = client_ip.split(',')[0].strip() if client_ip else 'unknown'
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))
    CORRELATION_ID.set(correlation_id)

    now = time.monotonic()
    with _rate_limit_lock:
        request_times = _rate_limit_state[client_ip]
        cutoff = now - RATE_LIMIT_WINDOW_SECONDS
        while request_times and request_times[0] < cutoff:
            request_times.popleft()

        if len(request_times) >= RATE_LIMIT_MAX_REQUESTS:
            retry_after = max(1, int(RATE_LIMIT_WINDOW_SECONDS - (now - request_times[0])))
            RATE_LIMIT_HITS.labels(client_ip=client_ip).inc()
            log.warning(
                'request.rate_limited',
                path=request.url.path,
                method=request.method,
                client_ip=client_ip,
                retry_after=retry_after,
                correlation_id=correlation_id,
            )
            return JSONResponse(
                status_code=429,
                content={
                    'detail': 'Rate limit exceeded',
                    'retry_after_seconds': retry_after,
                    'correlation_id': correlation_id,
                },
                headers={
                    'Retry-After': str(retry_after),
                    'X-Correlation-Id': correlation_id,
                },
            )

        request_times.append(now)

    start = time.perf_counter()

    log.info('request.started',
             path=request.url.path,
             method=request.method,
             correlation_id=correlation_id)

    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

    log.info('request.completed',
             path=request.url.path,
             status=response.status_code,
             latency_ms=elapsed_ms,
             correlation_id=correlation_id)

    response.headers['X-Correlation-Id'] = correlation_id
    return response

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    amount = float(body.get('amount', 0))
    PAYMENT_AMOUNT.observe(amount)
    log.info(
        'payment.received',
        amount=body.get('amount'),
        currency=body.get('currency', 'GBP'),
        correlation_id=CORRELATION_ID.get(),
    )
    downstream_result = await call_mock_downstream_echo(amount=amount, currency=body.get('currency', 'GBP'))
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', 'downstream': downstream_result, **body}


@app.get('/mock-downstream/echo')
async def mock_downstream_echo(request: Request):
    return {
        'received_correlation_id': request.headers.get('X-Correlation-Id'),
        'received_path': request.url.path,
    }


async def inject_correlation_id(request: httpx.Request) -> None:
    correlation_id = CORRELATION_ID.get()
    if correlation_id:
        request.headers['X-Correlation-Id'] = correlation_id


async def call_mock_downstream_echo(amount: float, currency: str) -> dict:
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(
        transport=transport,
        base_url='http://testserver',
        event_hooks={'request': [inject_correlation_id]},
    ) as client:
        response = await client.get(
            '/mock-downstream/echo',
            params={'amount': amount, 'currency': currency},
        )
        response.raise_for_status()
        return response.json()

print('✅ Logging middleware and routes defined')

"""---
## Part 3 — Prometheus Metrics Middleware

The four golden signals: **Latency, Traffic, Errors, Saturation**. We track all four with Prometheus counters and histograms.
"""

from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from prometheus_fastapi_instrumentator import Instrumentator
from fastapi.responses import Response

# Custom business metrics
PAYMENT_AMOUNT = Histogram(
    'payment_amount_gbp', 'Payment amount in GBP',
    buckets=[10, 50, 100, 500, 1000, 5000, 10000]
)

ERROR_COUNT = Counter(
    'payment_errors_total', 'Total payment processing errors',
    ['error_type']
)

RATE_LIMIT_HITS = Counter(
    'rate_limit_hits_total', 'Total requests rejected by the rate limiter',
    ['client_ip']
)

# Auto-instrument all HTTP routes (latency, status codes, method)
Instrumentator().instrument(app).expose(app)

print('✅ Prometheus metrics instrumented')
print('   → /metrics endpoint is now available')
print('   → Tracking: request_count, request_latency, payment_amount')

"""---
## Part 4 — Retry Logic with Tenacity

Payment APIs are flaky under load. We use `tenacity` to retry failed calls with **exponential backoff + jitter** to avoid the thundering herd problem.
"""

import random
import asyncio
from tenacity import (
    retry, stop_after_attempt, wait_exponential,
    retry_if_exception_type, before_sleep_log
)

# Simulate a flaky downstream fraud-check service
call_count = 0

async def flaky_fraud_check(payload: dict) -> dict:
    global call_count
    call_count += 1
    # Fail the first 2 attempts, succeed on 3rd
    if call_count < 3:
        print(f'  ⚠️  Attempt {call_count}: fraud API timeout (simulated)')
        raise ConnectionError(f'Fraud API timeout on attempt {call_count}')
    print(f'  ✅ Attempt {call_count}: fraud check passed')
    return {'fraud_score': 0.02, 'decision': 'approved'}


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=1, min=0.1, max=2),  # seconds (small for demo)
    retry=retry_if_exception_type((ConnectionError, TimeoutError)),
    reraise=True
)
async def call_fraud_api_with_retry(payload: dict) -> dict:
    return await flaky_fraud_check(payload)


# Test it
print('🔄 Testing retry logic...')
result = asyncio.run(
    call_fraud_api_with_retry({'amount': 1500, 'currency': 'GBP'})
)
print(f'\n📦 Final result: {result}')

"""---
## Part 5 — Circuit Breaker with PyBreaker

If a downstream service is consistently failing, retrying indefinitely makes things **worse**. The circuit breaker trips after `N` failures and returns a fast fallback for 30 seconds — preventing cascade failures.
"""

import pybreaker

class LoggingListener(pybreaker.CircuitBreakerListener):
    def state_change(self, cb, old_state, new_state):
        log.warning('circuit_breaker.state_change',
                    breaker=cb.name,
                    old=str(old_state),
                    new=str(new_state))

fraud_breaker = pybreaker.CircuitBreaker(
    fail_max=3,
    reset_timeout=30,
    listeners=[LoggingListener()],
    name='fraud-api'
)

def check_fraud_cb(payload: dict) -> dict:
    """Wrapped by circuit breaker — raises CircuitBreakerError when OPEN."""
    # Simulate always-failing service for demo
    raise ConnectionError('Fraud service down')

def safe_fraud_check(payload: dict) -> dict:
    """Call fraud API with circuit breaker; return fallback if circuit is OPEN."""
    try:
        return fraud_breaker.call(check_fraud_cb, payload)
    except pybreaker.CircuitBreakerError:
        print('🔴 Circuit OPEN — returning safe fallback (manual review)')
        return {'fraud_score': None, 'decision': 'manual_review', 'circuit': 'open'}
    except Exception as e:
        return {'fraud_score': None, 'decision': 'error', 'reason': str(e)}

print('📊 Simulating calls to a failing fraud service...')
for i in range(6):
    result = safe_fraud_check({'amount': 200 * (i + 1)})
    print(f'  Call {i+1}: {result} | Circuit state: {fraud_breaker.current_state}')

"""---
## Part 6 — Run the Full App

We start uvicorn in the background and expose it via a public ngrok tunnel so you can hit it from your browser or Postman.
"""

import os
import threading, uvicorn
from pyngrok import ngrok, conf
from pyngrok.exception import PyngrokNgrokError
from dotenv import load_dotenv

project_root = Path(__file__).resolve().parents[1]
load_dotenv(project_root / '.env', override=True)

NGROK_TOKEN = os.getenv('NGROK_AUTHTOKEN', '').strip()
print("-----------------",NGROK_TOKEN)
USE_NGROK = bool(NGROK_TOKEN)

if USE_NGROK:
    conf.get_default().auth_token = NGROK_TOKEN
# print("-----------------",USE_NGROK)
def run_server():
    uvicorn.run(app, host='0.0.0.0', port=8000, log_level='warning')

thread = threading.Thread(target=run_server, daemon=True)
thread.start()

import time; time.sleep(2)
public_url = 'http://127.0.0.1:8000'

if USE_NGROK:
    try:
        tunnel = ngrok.connect(8000)
        public_url = tunnel.public_url
    except PyngrokNgrokError as exc:
        print(f'âš ï¸ ngrok failed to start: {exc}')
        print('   Falling back to local access at http://127.0.0.1:8000')
else:
    print('âš ï¸ NGROK_AUTHTOKEN is not set, so the app will use localhost only.')

print(f'🌐 Public URL: {public_url}')
print(f'   Health:   {public_url}/health/ready')
print(f'   Metrics:  {public_url}/metrics')
print(f'   Docs:     {public_url}/docs')

# Quick smoke tests using httpx
import httpx, json

BASE = public_url  # set in the cell above

with httpx.Client() as client:
    # 1 — Health check
    r = client.get(f'{BASE}/health/ready')
    print('Health:', r.json())

    # 2 — POST a payment (watch structured logs above)
    r = client.post(f'{BASE}/payments',
                    json={'amount': 1500, 'currency': 'GBP', 'account': 'ACC-42'},
                    headers={'X-Correlation-Id': 'demo-corr-001'})
    print('Payment:', r.json())
    print('Returned correlation ID:', r.headers.get('X-Correlation-Id'))

    # 3 — Peek at first 500 chars of /metrics
    r = client.get(f'{BASE}/metrics')
    print('\nMetrics (first 500 chars):')
    print(r.text[:500])

"""---
## 🔥 Extension Tasks

### Extension A — Rate-Limiting Middleware *(Medium)*
Add a sliding-window rate limiter (e.g., 100 req/min per client IP) using an in-memory dictionary.
- Return `429 Too Many Requests` with a `Retry-After` header when the limit is exceeded
- Track limit hits as a Prometheus `Counter`

### Extension B — Correlation ID Propagation *(Medium)*
The current middleware assigns a correlation ID but does NOT forward it to outbound `httpx` calls.
- Add a `contextvars.ContextVar` to store the correlation ID per request
- Write a custom `httpx.Auth` or event hook that injects `X-Correlation-Id` into every outbound call
- Verify it appears in mock downstream requests

### Extension C — Prometheus + Grafana Dashboard *(Advanced)*
- Export your running `/metrics` to a free [Grafana Cloud](https://grafana.com/products/cloud/) account using the Prometheus remote-write endpoint
- Build a dashboard with 4 panels: request rate, p99 latency, error rate, circuit breaker trip count

### Extension D — Structured Log Aggregation *(Advanced)*
- Set up a free [Elastic Cloud](https://www.elastic.co/cloud/) cluster or use the Colab local filesystem
- Configure `structlog` to write logs as newline-delimited JSON to a file
- Write a query that finds all requests with `latency_ms > 200` for a specific `correlation_id`
"""
